name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set API_KEY environment variable
        run: echo "REACT_APP_API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Set AUTH_DOMAIN environment variable
        run: echo "REACT_APP_AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> .env

      - name: Set PROJECT_ID environment variable
        run: echo "REACT_APP_PROJECT_ID=${{ secrets.PROJECT_ID }}" >> .env

      - name: Set STORAGE_BUCKET environment variable
        run: echo "REACT_APP_STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> .env

      - name: Set MESSAGING_SENDER_ID environment variable
        run: echo "REACT_APP_MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> .env

      - name: Set APP_ID environment variable
        run: echo "REACT_APP_APP_ID=${{ secrets.APP_ID }}" >> .env

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
